let config = {
  SCHOLAR_POST_LIST_COVER:
    process.env.NEXT_PUBLIC_SCHOLAR_POST_LIST_COVER || !0,
  SCHOLAR_POST_LIST_CATEGORY:
    process.env.NEXT_PUBLIC_SCHOLAR_POST_LIST_CATEGORY || !0,
  SCHOLAR_POST_LIST_TAG: process.env.NEXT_PUBLIC_SCHOLAR_POST_LIST_TAG || !0,
  SCHOLAR_POST_DETAIL_CATEGORY:
    process.env.NEXT_PUBLIC_SCHOLAR_POST_DETAIL_CATEGORY || !0,
  SCHOLAR_POST_DETAIL_TAG:
    process.env.NEXT_PUBLIC_SCHOLAR_POST_DETAIL_TAG || !0,
  SCHOLAR_MENU_CATEGORY: process.env.NEXT_PUBLIC_SCHOLAR_MENU_CATEGORY || !0,
  SCHOLAR_MENU_TAG: process.env.NEXT_PUBLIC_SCHOLAR_MENU_TAG || !0,
  SCHOLAR_MENU_ARCHIVE: process.env.NEXT_PUBLIC_SCHOLAR_MENU_ARCHIVE || !0,
  SCHOLAR_MENU_SEARCH: process.env.NEXT_PUBLIC_SCHOLAR_MENU_SEARCH || !0,
  SCHOLAR_HOME_CATEGORY_LIMIT:
    process.env.NEXT_PUBLIC_SCHOLAR_HOME_CATEGORY_LIMIT || 6,
  SCHOLAR_HOME_TAG_LIMIT: process.env.NEXT_PUBLIC_SCHOLAR_HOME_TAG_LIMIT || 8,
  SCHOLAR_WIDGET_TO_TOP: !0
}
export default config
