import * as StyleModule from 'styled-jsx/style'
let Style = () => (
  <StyleModule.default id='21d2c3f1e4f06e1'>
    {
      '.dark body{background-color:#111827}#theme-scholar{--scholar-paper:#f4f1ea;--scholar-paper-strong:#fffdf8;--scholar-paper-soft:#f7f2e7;--scholar-ink:#1f2937;--scholar-muted:#5b6472;--scholar-border:#d9d0c3;--scholar-accent:#7a5c3e;--scholar-accent-dark:#c9a97c;--scholar-shadow:0 18px 40px rgba(15, 23, 42, 0.06)}#theme-scholar .scholar-shell{color:var(--scholar-ink)}#theme-scholar .scholar-panel,#theme-scholar .scholar-sidebar-card,#theme-scholar .scholar-hero-card{background:var(--scholar-paper-strong);border:1px solid var(--scholar-border);-webkit-box-shadow:var(--scholar-shadow);-moz-box-shadow:var(--scholar-shadow);box-shadow:var(--scholar-shadow)}#theme-scholar .scholar-eyebrow{color:var(--scholar-accent);letter-spacing:.35em;text-transform:uppercase;font-size:.72rem}#theme-scholar .scholar-serif{font-family:Bitter,"Noto Serif SC",Georgia,serif}#theme-scholar .scholar-sans{font-family:"Noto Sans SC","PingFang SC",sans-serif}#theme-scholar .scholar-muted{color:var(--scholar-muted)}#theme-scholar .notion{font-family:"Noto Sans SC","PingFang SC",sans-serif}#theme-scholar .notion-h,#theme-scholar .notion h1,#theme-scholar .notion h2,#theme-scholar .notion h3{font-family:Bitter,"Noto Serif SC",Georgia,serif;color:var(--scholar-ink)}#theme-scholar .notion-text,#theme-scholar .notion p,#theme-scholar .notion li,#theme-scholar .notion blockquote{line-height:1.95;color:#334155}#theme-scholar .notion blockquote{border-left:3px solid var(--scholar-accent);background:#faf6ee;padding:1rem 1.25rem;-webkit-border-radius:0 18px 18px 0;-moz-border-radius:0 18px 18px 0;border-radius:0 18px 18px 0}#theme-scholar .notion-table-of-contents-item{display:block;padding:.15rem 0}#theme-scholar .catalog-item-active{color:var(--scholar-accent);font-weight:700;text-decoration:underline;text-underline-offset:.2rem}#theme-scholar .scholar-divider{border-color:var(--scholar-border)}.dark #theme-scholar{--scholar-paper:#0f172a;--scholar-paper-strong:#111827;--scholar-paper-soft:#172033;--scholar-ink:#e5e7eb;--scholar-muted:#cbd5e1;--scholar-border:#334155;--scholar-accent:#c9a97c;--scholar-accent-dark:#e2c39a;--scholar-shadow:0 18px 40px rgba(2, 6, 23, 0.35)}.dark #theme-scholar .notion-text,.dark #theme-scholar .notion p,.dark #theme-scholar .notion li,.dark #theme-scholar .notion blockquote,.dark #theme-scholar .notion-h,.dark #theme-scholar .notion h1,.dark #theme-scholar .notion h2,.dark #theme-scholar .notion h3{color:#e5e7eb}.dark #theme-scholar .notion blockquote{background:#172033}'
    }
  </StyleModule.default>
)
export { Style }
